apiVersion: v2
name: rstudio-launcher-rbac
description: RBAC definition for the RStudio Job Launcher
type: application
version: 0.2.25
appVersion: 0.2.21
icon: https://raw.githubusercontent.com/rstudio/helm/main/images/posit-icon-fullcolor.svg
sources:
  - https://github.com/rstudio/helm
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/sol-eng
dependencies:
  - name: rstudio-library
    version: 0.1.31
    repository: https://helm.rstudio.com
keywords:
  - "data science"
  - "machine learning"
  - "launcher"
  - "rbac"
  - "rstudio"
  - "posit"
