apiVersion: v2
name: rstudio-launcher-rbac
description: RBAC definition for the RStudio Job Launcher
type: application
version: 0.2.17
appVersion: 0.2.17
icon: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
sources:
  - https://github.com/rstudio/helm
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/sol-eng
dependencies:
  - name: rstudio-library
    version: 0.1.26
    repository: file://../rstudio-library
keywords:
  - "data science"
  - "machine learning"
  - "launcher"
  - "rbac"
  - "rstudio"
