name: rstudio-workbench
description: Official Helm chart for RStudio Workbench
version: 0.5.29
apiVersion: v2
appVersion: 2022.12.0
icon: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
home: https://www.rstudio.com
sources:
  - https://github.com/rstudio/helm
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/sol-eng
dependencies:
  - name: rstudio-library
    version: 0.1.25
    repository: file://../rstudio-library
annotations:
  artifacthub.io/images: |
    - name: rstudio-workbench
      image: rstudio/rstudio-workbench:bionic-2022.12.0
    - name: r-session-complete
      image: rstudio/r-session-complete:bionic-2022.12.0
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Docker Images
      url: https://github.com/rstudio/rstudio-docker-products
    - name: RStudio Community
      url: https://community.rstudio.com/c/r-admin/5
    - name: About Workbench
      url: https://www.rstudio.com/products/workbench/
    - name: About RStudio Team
      url: https://www.rstudio.com/products/team/
keywords:
  - "data science"
  - "machine learning"
  - "r"
  - "rstats"
  - "python"
  - "ide"
  - "editor"
  - "jupyter"
  - "vscode"
  - "rstudio"
