apiVersion: v2
name: rstudio-library
description: Helm library helpers for use by Official RStudio charts
type: library
version: 0.1.18
appVersion: 0.1.18
icon: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
home: https://www.rstudio.com
sources:
  - https://github.com/rstudio/helm
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/rstudio/helm
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: RStudio Community
      url: https://community.rstudio.com/c/r-admin/5
    - name: About RStudio Team
      url: https://www.rstudio.com/products/team/
keywords:
  - "rstudio"
  - "library"
