apiVersion: v2
name: rstudio-library
description: Helm library helpers for use by official RStudio charts
type: library
version: 0.1.35
appVersion: 0.1.35

icon: https://raw.githubusercontent.com/rstudio/helm/main/images/posit-icon-fullcolor.svg
home: https://www.rstudio.com
sources:
  - https://github.com/rstudio/helm
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/rstudio/helm
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: RStudio Community
      url: https://community.rstudio.com/c/r-admin/5
    - name: About RStudio Team
      url: https://www.rstudio.com/products/team/
keywords:
  - "rstudio"
  - "library"
  - "posit"
