license:
  key: test
nodePort: 32420
metricsNodePort: 32112
replicas: 1
config:
  HTTP:
    Listen: :4242
  Server:
    DataDir: /var/lib/rstudio-pm
    RVersion:
      - /opt/R/default
  Git:
    BuilderDir: "/tmp/git"
