image:
  repository: rstudio/rstudio-package-manager
  tag: 1.1.6.1-5
  imagePullPolicy: Always
  imagePullSecrets:
    - name: "some-secret"

podDisruptionBudget:
  minAvailable: 30%

sharedStorage:
  create: true
  storageClassName: test-class
  volumeName: test-volume
license:
  key: test
service:
  type: NodePort
  annotations:
    key: value
    key2: value2
  nodePort: 32420
replicas: 1
config:
  HTTP:
    Listen: :4242
  Server:
    DataDir: /var/lib/rstudio-pm
    RVersion:
      - /opt/R/3.6.2
  Git:
    BuilderDir: "/tmp/git"
rstudioPMKey: somevalue
awsAccessKeyId: keyid
awsSecretAccessKey: keysecret
storageClaim: someClaimName

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

  # Defines network routing in the traefik configuration.
  hosts:
    - host: rspm.rstudio.com
      paths:
        - /


command: '["sleep","1000"]'
args: '[]'

initContainers:
  - name: busybox
    image: busybox
    command: ["echo"]
    args: ["init"]

extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "test"
    data:
      something: fun
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "test2"
    data:
      something: {{ printf "fun2" }}

pod:
  labels:
    onelabel.com: value
priorityClassName: someval

# Testing with the chronicle-agent sidecar container
extraContainers:
  - name: chronicle-agent
    image: ghcr.io/rstudio/chronicle-agent:2024.11.0
    imagePullPolicy: Always
    env:
    - name: CHRONICLE_SERVER_ADDRESS
      value: "http://chronicle-server.default"
