config:
  sessionSecret:
    example-file.json: '{"some-contents": "test"}'
launcher:
  enabled: true
  useTemplates: true
  templateValues:
    service:
      type: ClusterIP
      annotations:
        five: six
    job:
      annotations:
        seven: eight
      labels:
        nine: ten
    pod:
      serviceAccountName: test
      annotations:
        one: two
      labels:
        three: four
      volumes:
        - name: test
          emptyDir: {}
      volumeMounts:
        - name: test
          mountPath: /tmp/mnt
      securityContext:
        runAsUser: 999
      defaultSecurityContext:
        fsGroupChangePolicy: "Always"
        runAsGroup: 999
      containerSecurityContext:
        privileged: false
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.azure.com/scalesetpriority"
                    operator: In
                    values:
                      - "spot"
