name: rstudio-pm
description: Official Helm chart for Posit Package Manager
version: 0.5.44
apiVersion: v2
appVersion: 2024.11.0
icon: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
home: https://www.rstudio.com
sources:
  - https://github.com/rstudio/helm
  - https://github.com/rstudio/rstudio-docker-products
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/rstudio/helm
dependencies:
  - name: rstudio-library
    version: 0.1.31
    repository: https://helm.rstudio.com
annotations:
  artifacthub.io/images: |
    - name: rstudio-package-manager
      image: rstudio/rstudio-package-manager:ubuntu2204-2024.11.0
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: RStudio Community
      url: https://community.rstudio.com/c/r-admin/5
    - name: About Package Manager
      url: https://posit.co/products/enterprise/package-manager/
    - name: About Posit Team
      url: https://posit.co/products/enterprise/team/
keywords:
  - "data science"
  - "machine learning"
  - "r"
  - "rstats"
  - "python"
  - "package"
  - "cran"
  - "pypi"
  - "pip"
  - "bioconductor"
  - "rstudio"
  - "posit"
