name: rstudio-connect
description: Official Helm chart for Posit Connect
version: 0.8.4
apiVersion: v2
appVersion: 2025.05.0
icon: https://rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-Flat.png
home: https://www.rstudio.com
sources:
  - https://github.com/rstudio/helm
maintainers:
  - name: sol-eng
    email: docker@rstudio.com
    url: https://github.com/sol-eng
dependencies:
  - name: rstudio-library
    version: 0.1.34
    repository: https://helm.rstudio.com
annotations:
  artifacthub.io/images: |
    - name: rstudio-connect
      image: rstudio/rstudio-connect:ubuntu2204-2025.05.0
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Docker Images
      url: https://github.com/rstudio/rstudio-docker-products
    - name: RStudio Community
      url: https://community.rstudio.com/c/r-admin/5
    - name: About Connect
      url: https://www.rstudio.com/products/connect/
    - name: About RStudio Team
      url: https://www.rstudio.com/products/team/
keywords:
  - "data science"
  - "machine learning"
  - "r"
  - "rstats"
  - "python"
  - "deploy"
  - "rstudio"
  - "posit"
