name: Kubernetes
images:
  -
    name: ghcr.io/rstudio/content-base:r3.1.3-py2.7.18-bionic
    python:
      installations:
        -
          path: /opt/python/2.7.18/bin/python2.7
          version: 2.7.18
    r:
      installations:
        -
          path: /opt/R/3.1.3/bin/R
          version: 3.1.3
  -
    name: ghcr.io/rstudio/content-base:r3.2.5-py2.7.18-bionic
    python:
      installations:
        -
          path: /opt/python/2.7.18/bin/python2.7
          version: 2.7.18
    r:
      installations:
        -
          path: /opt/R/3.2.5/bin/R
          version: 3.2.5
  -
    name: ghcr.io/rstudio/content-base:r3.3.3-py3.6.13-bionic
    python:
      installations:
        -
          path: /opt/python/3.6.13/bin/python3.6
          version: 3.6.13
    r:
      installations:
        -
          path: /opt/R/3.3.3/bin/R
          version: 3.3.3
  -
    name: ghcr.io/rstudio/content-base:r3.4.4-py3.6.13-bionic
    python:
      installations:
        -
          path: /opt/python/3.6.13/bin/python3.6
          version: 3.6.13
    r:
      installations:
        -
          path: /opt/R/3.4.4/bin/R
          version: 3.4.4
  -
    name: ghcr.io/rstudio/content-base:r3.5.3-py3.7.10-bionic
    python:
      installations:
        -
          path: /opt/python/3.7.10/bin/python3.7
          version: 3.7.10
    r:
      installations:
        -
          path: /opt/R/3.5.3/bin/R
          version: 3.5.3
  -
    name: ghcr.io/rstudio/content-base:r3.6.3-py3.8.8-bionic
    python:
      installations:
        -
          path: /opt/python/3.8.8/bin/python3.8
          version: 3.8.8
    r:
      installations:
        -
          path: /opt/R/3.6.3/bin/R
          version: 3.6.3
  -
    name: ghcr.io/rstudio/content-base:r4.0.5-py3.8.8-bionic
    python:
      installations:
        -
          path: /opt/python/3.8.8/bin/python3.8
          version: 3.8.8
    r:
      installations:
        -
          path: /opt/R/4.0.5/bin/R
          version: 4.0.5
  -
    name: ghcr.io/rstudio/content-base:r4.0.5-py3.9.2-bionic
    python:
      installations:
        -
          path: /opt/python/3.9.2/bin/python3.9
          version: 3.9.2
    r:
      installations:
        -
          path: /opt/R/4.0.5/bin/R
          version: 4.0.5

  -
    name: ghcr.io/rstudio/content-base:r4.1.0-py3.8.8-bionic
    python:
      installations:
        -
          path: /opt/python/3.8.8/bin/python3.8
          version: 3.8.8
    r:
      installations:
        -
          path: /opt/R/4.1.0/bin/R
          version: 4.1.0
  -
    name: ghcr.io/rstudio/content-base:r4.1.0-py3.9.2-bionic
    python:
      installations:
        -
          path: /opt/python/3.9.2/bin/python3.9
          version: 3.9.2
    r:
      installations:
        -
          path: /opt/R/4.1.0/bin/R
          version: 4.1.0
